name: CMake Build with SFML

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/ishiguro96/ubuntu-planszowker:latest
      credentials:
        username: ishiguro96
        password: ${{ secrets.DOCKER_ACTIONS }}

    steps:
      - uses: actions/checkout@v2
      - name: Create Build Environment
        shell: bash
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        shell: bash
        run: ls -al; pwd; cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: build
        shell: bash
        run: cmake --build . --config Release

      - name: Test
        working-directory: build
        shell: bash
        run: ctest -C Release
