name: CMake Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/planszowker/planszowker-docker:latest

    steps:
      - name: Install dependencies
        shell: bash
        run: |
          apt update && \
          apt install -y --no-install-recommends \
          autoconf \
          automake \
          build-essential \
          ca-certificates \
          cmake \
          curl \
          g++ \
          gcc \
          git \
          libgl1-mesa-dev \
          libtool \
          libudev-dev \
          libx11-dev \
          libxcursor-dev \
          libxi-dev \
          libxrandr-dev \
          make \
          ninja-build \
          pkg-config \
          python-is-python3 \
          python3 \
          python3-pip \
          sudo \
          tar \
          unzip \
          zip

      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: '#13-Kingdomino_game_adaptation' # For now, it is fixed to this branch. Remove it when master is ready

      - name: Configure VCPKG
        shell: bash
        run: |
          ./vcpkg/bootstrap-vcpkg.sh
          export VCPKG_FORCE_SYSTEM_BINARIES=1
          export VCPKG_DEFAULT_HOST_TRIPLET=arm64-linux
          ./vcpkg/vcpkg install

      - name: Configure CMake
        shell: bash
        run: cmake -B ./build -S. -DCMAKE_BUILD_TYPE=Release --preset=default-linux

      - name: Build
        shell: bash
        run: cmake --build ./build --config Release --parallel 32

      - name: Test
        shell: bash
        working-directory: build
        run: ctest -C Release
