name: CMake Build with SFML

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/ishiguro96/ubuntu-planszowker:latest
      credentials:
        username: ishiguro96
        password: ${{ secrets.DOCKER_ACTIONS }}

    steps:
      - name: Create Build Environment
        shell: bash
        run: mkdir -p build

      - uses: actions/checkout@v2
      - name: Configure CMake
        shell: bash
        run: cd build && echo ${{github.workspace}}; ls -al ${{github.workspace}}; cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release

      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: cd build && cmake --build . --config Release

      - uses: actions/checkout@v2
      - name: Test
        shell: bash
        run: cd build && ctest -C Release
